### ISSUE TITLE
Unit conventions and files

### ISSUE THREAD

**Issue by andersx** [RowleyGroup/torsionbenchmark#1]
First off, thank you so much for sharing this!

Just to clarify two points before I run my own benchmarks on this dataset:

1. Are the `xyz` files in `torsionbenchmark/torsionbenchmark/ccsd/struct/`the files I should run my PES benchmark on? There are similar PDB files in some of the folders, but these only seem to serve for atomtyping for MM FFs.
2. What are the units in the `.csv` files? I'm guessing kcal/mol, but would be great to have this confirmed!

Thank you!

**Comment by cnrowley** [comment]
Sorry, I'm in the middle of a review panel this week and won't be able to look into this seriously for another week. The pdb's and xyz's _should_  be consistent, but it's possible the atom numbering isn't the same (i.e., you should be able to use the PDB's for coordinates too). 

The csv files are in kcal/mol

**Comment by andersx** [comment]
Thank you, that is all I needed to know!
